stages:
  - security

checkov_scan:
  stage: security
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d . -o json --soft-fail > checkov-report.json
  artifacts:
    paths:
      - checkov-report.json
    when: always
    expire_in: 1 week

trivy_iac_scan:
  stage: security
  image:
    name: aquasec/trivy
    entrypoint: [""]
  script:
    - trivy config --format json --output trivy-report.json .
  artifacts:
    paths:
      - trivy-report.json
    when: always
    expire_in: 1 week

gitleaks:
  stage: security
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script:
    - gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json --no-git
  artifacts:
    paths:
      - gitleaks-report.json
    when: always
    expire_in: 1 week
