stages:
  - security

checkov_scan:
  stage: security
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d . --soft-fail
  only:
    - main
    - merge_requests

