stages:
  - lint
  - security

tflint:
  stage: lint
  image: ghcr.io/terraform-linters/tflint
  script:
    - tflint --init
    - tflint --format=json > tflint-report.json
  artifacts:
    paths:
      - tflint-report.json
    when: always
    expire_in: 1 week

checkov_scan:
  stage: security
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d . -o json > checkov-report.json
  artifacts:
    paths:
      - checkov-report.json
    when: always
    expire_in: 1 week

tfsec_scan:
  stage: security
  image: aquasec/tfsec
  script:
    - tfsec . --format json --out tfsec-report.json
  artifacts:
    paths:
      - tfsec-report.json
    when: always
    expire_in: 1 week

gitleaks:
  stage: security
  image: zricethezav/gitleaks
  script:
    - gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json
  artifacts:
    paths:
      - gitleaks-report.json
    when: always
    expire_in: 1 week
