stages:
  - security

checkov_scan:
  stage: security
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  script:
    - checkov -d . -o json --soft-fail > checkov-report.json
  artifacts:
    paths:
      - checkov-report.json
    when: always
    expire_in: 1 week

tfsec_scan:
  stage: security
  image: aquasec/tfsec
  script:
    - tfsec . --format json --out tfsec-report.json
  artifacts:
    paths:
      - tfsec-report.json
    when: always
    expire_in: 1 week

gitleaks:
  stage: security
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script:
    - gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json --no-git
  artifacts:
    paths:
      - gitleaks-report.json
    when: always
    expire_in: 1 week
